version: '3'
services:
  client:
    image: ${DOCKER_HUB_USERNAME}/dp-aws-client:${SHA}
    mem_limit: 128m
    hostname: client
    environment:
      - WDS_SOCKET_PORT=0
  api:
    image: ${DOCKER_HUB_USERNAME}/dp-aws-server:${SHA}
    mem_limit: 128m
    hostname: api
    restart: always
    environment:
      - REDIS_HOST=${RHOST}
      - REDIS_PORT=6379
      - PGUSER=${PGUSER}
      - PGHOST=${PGHOST}
      - PGDATABASE=${PGDATABASE}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGPORT=5432
  worker:
    image: ${DOCKER_HUB_USERNAME}/dp-aws-worker:${SHA}
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=${RHOST}
      - REDIS_PORT=6379
  nginx:
    image: ${DOCKER_HUB_USERNAME}/dp-aws-nginx:${SHA}
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'


