name: Fibonacci App Prod Deployment
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# env:
#   GH_TOKEN: ${{ secrets.BAZEL_IO_TOKEN }}


jobs:
  # Test
  # test-client:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3  # Tells the robot to "git clone" your code
      
  #     - name: Build the Test Image
  #       run: docker build -t ian/react-test -f ./client/Dockerfile.dev ./client
        
  #     - name: Run Tests
  #       run: docker run -e CI=true ian/react-test npm test

  build:
    # needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build the Docker images
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build Docker images and push
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/dp-aws-nginx:${{ github.sha }} -f ./nginx/Dockerfile ./nginx
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/dp-aws-client:${{ github.sha }} -f ./client/Dockerfile ./client
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/dp-aws-server:${{ github.sha }} -f ./server/Dockerfile ./server
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/dp-aws-worker:${{ github.sha }} -f ./worker/Dockerfile ./worker
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/dp-aws-nginx:${{ github.sha }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/dp-aws-client:${{ github.sha }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/dp-aws-server:${{ github.sha }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/dp-aws-worker:${{ github.sha }}
        shell: bash

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change this if your EC2 is in a different region
      
      - name: Deploy
        run: |
          aws ssm send-command \
            --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "cd /home/ec2-user",
              "rm -r app",
              "mkdir app",
              "cd app",
              "echo \"PGUSER=$(aws ssm get-parameter --name /dockerpractice/prod/PGUSER --with-decryption --query Parameter.Value --output text)\" > .env",
              "echo \"PGDATABASE=$(aws ssm get-parameter --name /dockerpractice/prod/PGDATABASE --with-decryption --query Parameter.Value --output text)\" >> .env",
              "echo \"POSTGRES_PASSWORD=$(aws ssm get-parameter --name /dockerpractice/prod/POSTGRES_PASSWORD --with-decryption --query Parameter.Value --output text)\" >> .env",
              "echo \"PGHOST=$(aws ssm get-parameter --name /dockerpractice/prod/PGHOST --with-decryption --query Parameter.Value --output text)\" >> .env",
              "echo \"SHA=${{ github.sha }}\" >> .env",
              "echo \"DOCKER_HUB_USERNAME=${{ secrets.DOCKER_HUB_USERNAME }}\" >> .env",
              
              "curl -L https://raw.githubusercontent.com/${{ github.repository }}/main/docker-compose.yml -o docker-compose.yml",
              "docker-compose down -v",
              "docker-compose down --remove-orphans",
              "docker-compose pull",
              "docker-compose up -d",
              "docker system prune -f",
              
            ]'
        shell: bash

      
# /dockerpractice/prod/POSTGRES_PASSWORD